### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by SSadistic** [R1KO/VIP-Core#10]
`SQL_Callback_SelectVipPlayers: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 60' at line 1`

**Comment by R1KO** [comment]
How VIP-Core version?

**Comment by SSadistic** [comment]
[VIP] Core 3.0 DEV #17

I deleted the old "vip_users" and "vip_overrides" because of that change "Теперь игроки хранятся в базе по AccountID." and I needed a new database. And I get that error when I try to list players.

**Comment by R1KO** [comment]
1. Set value 1 https://github.com/R1KO/VIP-Core/blob/new-style/addons/sourcemod/scripting/VIP_Core.sp#L11
2. Compile
3. Test and give me `VIP_Debug.log` (in `addons/sourcemod/logs/`)

**Comment by SSadistic** [comment]
`L 10/30/2017 - 20:47:53: [vipsystem/VIP_Core.smx] SELECT `o`.`group`, `o`.`expires`, `u`.`name`, `u`.`account_id`, `u`.`id` FROM `vip_users` AS `u` LEFT JOIN `vip_overrides` AS `o` ON `o`.`user_id` = `u`.`id` WHERE `o`.`server_id` = 1 AND `u`.`id` = 2 LIMIT 1;
L 10/30/2017 - 20:47:53: [vipsystem/VIP_Core.smx] SetValue(Time) = 1509392824
L 10/30/2017 - 20:47:53: [vipsystem/VIP_Core.smx] GetValue(Time) = 1509392824
L 10/30/2017 - 20:48:05: [vipsystem/VIP_Core.smx] MenuHandler_VipClientInfoMenu->MenuCancel_ExitBack
L 10/30/2017 - 20:48:05: [vipsystem/VIP_Core.smx] GetValue(MenuListType) = 2
L 10/30/2017 - 20:48:06: [vipsystem/VIP_Core.smx] SELECT `u`.`id`, `u`.`name` FROM `vip_users` AS `u` LEFT JOIN `vip_overrides` AS `o` ON `o`.`user_id` = `u`.`id` WHERE `o`.`server_id` = 1LIMIT 0, 60;
`

**Comment by SSadistic** [comment]
Also: https://i.imgur.com/G68nns5.jpg

This is very bugged too. Name: 0, Group: My SteamID, Expires: The Vip group, Identifier: Expires in

**Comment by R1KO** [comment]
Fix: Add space before `LIMIT` https://github.com/R1KO/VIP-Core/blob/new-style/addons/sourcemod/scripting/vip/adminmenu/List.sp#L219

About the fact that instead of nickname the symbol 0 I know. If you do not mind creating a new issue with this problem

**Comment by SSadistic** [comment]
From:

> 												LIMIT %d, %d;", 

To:

> 												 LIMIT %d, %d;", 


?

Or add space like the word space.

**Comment by R1KO** [comment]
yes
`LIMIT %d, %d;` -> ` LIMIT %d, %d;`

**Comment by SSadistic** [comment]
Those spaceings here are so bugged ffs... So I need to do that:

https://i.imgur.com/6UQ7bBv.gif

Or I got you wrong

**Comment by R1KO** [comment]
yes

**Comment by SSadistic** [comment]
Well, I still get:

> L 10/31/2017 - 00:30:38: [vipsystem/VIP_Core.smx] SQL_Callback_SelectVipPlayers: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 60' at line 1

**Comment by R1KO** [comment]
Test this version http://joxi.ru/V2VvvxdU0WM7j2

**Comment by SSadistic** [comment]
https://i.imgur.com/J3hY3hX.jpg

I guess those zeroes are from the other problem. Also - can I have

**Comment by R1KO** [comment]
Zeros now correct

> Also - can I have the plugins with Выход changed to Exit? I used to change it myself from the Info.sp, but I don't have it now.
More?

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/commit/8652ccdc2317e4fb3847e27e70c41c8628699da8
And
https://github.com/R1KO/VIP-Core/commit/272ccb5128a22843201e96a616bb5c31b09d8b8c

**Comment by R1KO** [comment]
@SSadistic 
Test this http://joxi.ru/bmobbD0CM0kJPr and me full `VIP_Debug.log`
Try adding a VIP player.

**Comment by SSadistic** [comment]
https://pastebin.com/7da48rBA

**Comment by R1KO** [comment]
in the database and menu the normal name?

**Comment by SSadistic** [comment]
I can't access the DB now, but the VIP is added as it should be. Still zeroes in listing players.

**Comment by R1KO** [comment]
In which case does the name change to 0?

**Comment by SSadistic** [comment]
https://i.imgur.com/A0TzneJ.jpg

**Comment by SSadistic** [comment]
All the names in List players are the same as before and when you click on any of them you get that which is on the picture.

**Comment by R1KO** [comment]
The name in the database when it becomes 0?
When adding VIP players, the name is normal?

**Comment by SSadistic** [comment]
I can't get you.. So I removed me from the DB (from the menu), than I re-added me. The ID is my Steam3 ID, so I guess it should be adding me on the MySQL as it should be, since I have the VIP extras. On list players is shows zeroes (0) as it's shown on the picture.

**Comment by R1KO** [comment]
how did you add a VIP player?
Through a command, through the menu or directly to the base?

**Comment by SSadistic** [comment]
Through the menu, but I can try with a command in the console.

**Comment by R1KO** [comment]
Попробуй

**Comment by SSadistic** [comment]
With name, #userid or identity? (sm_addvip <identity type> <name|#userid|identity> [time] [group] - добавляет VIP-игрока.).

**Comment by R1KO** [comment]
#name or #userid or #steam_id

**Comment by SSadistic** [comment]
] sm_addvip "STEAM_1:1:43707767" FreeVIP 120
 [VIP] VIP-player unknown (87415535, ID: 25) successfully added!

Still zeroes in List players.

**Comment by R1KO** [comment]
Give me `VIP_Debug.log`

**Comment by SSadistic** [comment]
https://pastebin.com/s8zQaz3u

There're some players in the server, but that should be.

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/commit/19495bb03b6e8333c6d074ade4bc581473796484
