### ISSUE TITLE
Проблемы

### ISSUE THREAD

**Issue by kleuser75** [R1KO/VIP-Core#11]
Версия 3.0 dev 19

Вообщем, как я в дискорде говорил, проблема с отображением ника в базе есть, отображает как Ноль, за место ника (в dev 19 так же).
И хочу спросить, что за аккаунт id, зачем убрал стим id ? ведь теперь нельзя перенести старых игроков на новую базу.

И еще немного ошибок, связных с поиском игроков
SourceMod error session started
Info (map "de_dust2") (file "errors_20171027.log")
[SM] Exception reported: Invalid Handle 0 (error 4)
[SM] Blaming: vip\VIP_Core.smx
[SM] Call stack trace:
[SM]   [0] StringMap.SetValue
[SM]   [1] Line 190, vip/AdminMenu/List.sp::ShowVipPlayersFromDBMenu
[SM]   [2] Line 83, vip/AdminMenu/List.sp::MenuHandler_VipPlayersListMenu
Error log file session closed.
SourceMod error session started
Info (map "de_dust2") (file "errors_20171027.log")
[SM] Exception reported: Invalid Handle 0 (error 4)
[SM] Blaming: vip\VIP_Core.smx
[SM] Call stack trace:
[SM]   [0] StringMap.SetValue
[SM]   [1] Line 190, vip/AdminMenu/List.sp::ShowVipPlayersFromDBMenu
[SM]   [2] Line 83, vip/AdminMenu/List.sp::MenuHandler_VipPlayersListMenu
[vip\VIP_Core.smx] SQL_Callback_SelectVipPlayers: near ")": syntax error

**Comment by R1KO** [comment]
> Вообщем, как я в дискорде говорил, проблема с отображением ника в базе есть, отображает как Ноль, за место ника (в dev 19 так же).
Нужно больше инфы когда такое происходит. При добавлении, при обновлении или при каком-то еще действии?
> И хочу спросить, что за аккаунт id, зачем убрал стим id ? 
Аккаунт ид более универсальный и экономный вариант.
> ведь теперь нельзя перенести старых игроков на новую базу.
Для этого будет модуль портирования
>И еще немного ошибок, связных с поиском игроков
Про ошибки знаю, ищу проблему.
>[vip\VIP_Core.smx] SQL_Callback_SelectVipPlayers: near ")": syntax error
А вот это интересно.
