### ISSUE TITLE
CI Build Error on SM 1.9

### ISSUE THREAD

**Issue by R1KO** [R1KO/VIP-Core#119]
![image](https://user-images.githubusercontent.com/5843406/212665753-62688fa4-f70a-4a48-bdb6-d46e4555d599.png)

@idk1703 can you fix it?

**Comment by idk1703** [comment]
Change to version `v1.1.0` (`rumblefrog/setup-sp@v1.1.0`).
Now `rumblefrog/setup-sp` using `spcomp64`, but in `1.9` he not exist. 
Or drop support `1.9`. (who use now `1.9` sourcemod ?)
