### ISSUE TITLE
List players is still bugged.

### ISSUE THREAD

**Issue by SSadistic** [R1KO/VIP-Core#12]
https://i.imgur.com/Gsd5hZl.jpg - Zeroes, only my name is normal.
https://i.imgur.com/urrUzNb.jpg - Group, Expires and Identifier are messed up.

**Comment by R1KO** [comment]
> https://i.imgur.com/Gsd5hZl.jpg - Zeroes, only my name is normal.

Other names will become normal after the players enter the server

>https://i.imgur.com/urrUzNb.jpg - Group, Expires and Identifier are messed up.

thanks. tomorrow I will fix it

**Comment by R1KO** [comment]
Checked in my - there is no problem.
If you updated from older versions - update the translation file

**Comment by R1KO** [comment]
@SSadistic Is there still a problem?

**Comment by SSadistic** [comment]
Can't tell you, since I cant get the plugin to hook the database to see the list.
