### ISSUE TITLE
Unknown column 'uid' in 'where clause'

### ISSUE THREAD

**Issue by SSadistic** [R1KO/VIP-Core#13]
> L 12/05/2017 - 21:22:06: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:08: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:09: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:09: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:12: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:14: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:20: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:22: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:23: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:29: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:33: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:38: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:38: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:39: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:40: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:41: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:22:49: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:23:20: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:23:37: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:29:14: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:32:53: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:33:48: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:40:03: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:45:29: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:47:48: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:48:01: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:50:35: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:52:35: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 21:57:35: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 22:00:22: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'
L 12/05/2017 - 22:00:44: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'

I used the latest version I think.

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/commit/39d7ebff517a93d3996f22efa1c5004096d85ca2
