### ISSUE TITLE
 v3.0 DEV #24  Исправлены SQL ошибки

### ISSUE THREAD

**Issue by SSadistic** [R1KO/VIP-Core#14]
> L 12/05/2017 - 22:48:39: Info (map "mg_saw_3_v1") (file "errors_20171205.log")
> L 12/05/2017 - 22:48:39: [vipsystem/VIP_Core.smx] SQL_Callback_OnClientAuthorized: Unknown column 'uid' in 'where clause'

Just updated the plugin

If I try to add to DB:

> L 12/05/2017 - 22:50:29: [vipsystem/VIP_Core.smx] SQL_Callback_OnVIPClientAdded: Unknown column 'uid' in 'field list'

**Comment by R1KO** [comment]
delete your database

**Comment by SSadistic** [comment]
Can I just edit the columns with are bugging?

**Comment by R1KO** [comment]
Yes. in accordance with https://github.com/R1KO/VIP-Core/blob/new-style/addons/sourcemod/scripting/vip/Database.sp#L87-L100

**Comment by R1KO** [comment]
@SSadistic The problem has disappeared?

**Comment by SSadistic** [comment]
It seems I must delete the DB, since it don't work if you change it and if i try to add a VIP i get "SQL_Callback_OnVIPClientAdded: Duplicate entry '87415535-1' for key 'user_id'"

So, will you make anymore changes in the name of the databases? If no, i'll delete it.

**Comment by R1KO** [comment]
@SSadistic 90% certainty that the database will no longer change

**Comment by SSadistic** [comment]
Okay, mark it as fixed than, the list is also fixed.
