### ISSUE TITLE
Не запускается на SourceMod 1.73

### ISSUE THREAD

**Issue by tengzl33t** [R1KO/VIP-Core#16]
Не получается запустить VIP-Core (new-style) на SourceMod 1.73-dev+5290
![default](https://user-images.githubusercontent.com/10462726/36669522-d84be486-1afd-11e8-82c6-b12dbd055bfc.PNG)
В databases.cfg 
![default](https://user-images.githubusercontent.com/10462726/36669642-3b528166-1afe-11e8-9830-3b973a603863.PNG)

**Comment by CrazyHackGUT** [comment]
И не получится.
Новая версия требует SM 1.8 или выше из-за синтаксиса.
