### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by kleuser75** [R1KO/VIP-Core#17]
[vip/VIP_Core.smx] SQL_Callback_SelectExpiredAndOutdated: no such column: iTime
Появляется при запуске сервера
SM 1.9
SQLite база
VIP CORE Dev#32

**Comment by R1KO** [comment]
В курсе. Уже решена. В следующем коммите будет фикс.

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/commit/fdd2552ff01cd0313c27894b1b5bc262f9d68883
