### ISSUE TITLE
v3.0 DEV #34 Проблемы с переводом и error'ы

### ISSUE THREAD

**Issue by Rostu13** [R1KO/VIP-Core#19]
Vip core #34
Спамит  при добавлении вип игрока 

> L 03/28/2018 - 11:37:26: [SM] Exception reported: Language phrase "ADMIN_ADD_VIP_PLAYER_SUCCESSFULLY" not found (arg 4)
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] FormatNativeString
L 03/28/2018 - 11:37:26: [SM]   [1] Line 279, vip/API.sp::Native_PrintToChatClient
L 03/28/2018 - 11:37:26: [SM]   [3] VIP_PrintToChatClient
L 03/28/2018 - 11:37:26: [SM]   [4] Line 373, vip/UTIL.sp::SQL_Callback_OnVIPClientAdded
L 03/28/2018 - 11:37:26: [SM] Exception reported: Language phrase "LOG_ADMIN_ADD_VIP_IDENTITY_SUCCESSFULLY" not found (arg 5)
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] LogToFile
L 03/28/2018 - 11:37:26: [SM]   [1] Line 382, vip/UTIL.sp::SQL_Callback_OnVIPClientAdded 

(Файлы перевода перезалил, такого на гите не увидел)

> 
L 03/28/2018 - 11:37:26: [SM] Exception reported: Plugin handle afe0155 is invalid (error 1)
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] Call_StartFunction
L 03/28/2018 - 11:37:26: [SM]   [1] Line 326, vip/VipMenu.sp::Function_OnItemToggle
L 03/28/2018 - 11:37:26: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 03/28/2018 - 11:37:26: [SM]   [3] Line 183, vip/Clients.sp::Clients_OnVIPClientLoaded
L 03/28/2018 - 11:37:26: [SM]   [4] Line 287, vip/Clients.sp::Clients_LoadVIPFeatures
L 03/28/2018 - 11:37:26: [SM]   [5] Line 237, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 03/28/2018 - 11:37:26: [SM]   [6] Line 169, vip/Clients.sp::SQL_Callback_OnClientAuthorized
L 03/28/2018 - 11:37:26: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] Call_PushCell
L 03/28/2018 - 11:37:26: [SM]   [1] Line 327, vip/VipMenu.sp::Function_OnItemToggle
L 03/28/2018 - 11:37:26: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 03/28/2018 - 11:37:26: [SM]   [3] Line 183, vip/Clients.sp::Clients_OnVIPClientLoaded
L 03/28/2018 - 11:37:26: [SM]   [4] Line 287, vip/Clients.sp::Clients_LoadVIPFeatures
L 03/28/2018 - 11:37:26: [SM]   [5] Line 237, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 03/28/2018 - 11:37:26: [SM]   [6] Line 169, vip/Clients.sp::SQL_Callback_OnClientAuthorized
L 03/28/2018 - 11:37:26: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] Call_PushString
L 03/28/2018 - 11:37:26: [SM]   [1] Line 328, vip/VipMenu.sp::Function_OnItemToggle
L 03/28/2018 - 11:37:26: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 03/28/2018 - 11:37:26: [SM]   [3] Line 183, vip/Clients.sp::Clients_OnVIPClientLoaded
L 03/28/2018 - 11:37:26: [SM]   [4] Line 287, vip/Clients.sp::Clients_LoadVIPFeatures
L 03/28/2018 - 11:37:26: [SM]   [5] Line 237, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 03/28/2018 - 11:37:26: [SM]   [6] Line 169, vip/Clients.sp::SQL_Callback_OnClientAuthorized
L 03/28/2018 - 11:37:26: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] Call_PushCell
L 03/28/2018 - 11:37:26: [SM]   [1] Line 329, vip/VipMenu.sp::Function_OnItemToggle
L 03/28/2018 - 11:37:26: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 03/28/2018 - 11:37:26: [SM]   [3] Line 183, vip/Clients.sp::Clients_OnVIPClientLoaded
L 03/28/2018 - 11:37:26: [SM]   [4] Line 287, vip/Clients.sp::Clients_LoadVIPFeatures
L 03/28/2018 - 11:37:26: [SM]   [5] Line 237, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 03/28/2018 - 11:37:26: [SM]   [6] Line 169, vip/Clients.sp::SQL_Callback_OnClientAuthorized
L 03/28/2018 - 11:37:26: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 11:37:26: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:37:26: [SM] Call stack trace:
L 03/28/2018 - 11:37:26: [SM]   [0] Call_PushCellRef
L 03/28/2018 - 11:37:26: [SM]   [1] Line 330, vip/VipMenu.sp::Function_OnItemToggle
L 03/28/2018 - 11:37:26: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 03/28/2018 - 11:37:26: [SM]   [3] Line 183, vip/Clients.sp::Clients_OnVIPClientLoaded
L 03/28/2018 - 11:37:26: [SM]   [4] Line 287, vip/Clients.sp::Clients_LoadVIPFeatures
L 03/28/2018 - 11:37:26: [SM]   [5] Line 237, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 03/28/2018 - 11:37:26: [SM]   [6] Line 169, vip/Clients.sp::SQL_Callback_OnClientAuthorized
>
UPD: При нажатии пункта в !vip меню происходит это (Сама менюшка работает (вкл/выкл + список) )

> L 03/28/2018 - 12:01:42: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 12:01:42: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 12:01:42: [SM] Call stack trace:
L 03/28/2018 - 12:01:42: [SM]   [0] Call_PushStringEx
L 03/28/2018 - 12:01:42: [SM]   [1] Line 224, vip/VipMenu.sp::Handler_VIPMenu
L 03/28/2018 - 12:01:42: [SM]   [3] Menu.DisplayAt
L 03/28/2018 - 12:01:42: [SM]   [4] Line 306, vip/VipMenu.sp::Handler_VIPMenu
L 03/28/2018 - 12:01:42: [SM] Exception reported: Cannot push parameters when there is no call in progress
L 03/28/2018 - 12:01:42: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 12:01:42: [SM] Call stack trace:
L 03/28/2018 - 12:01:42: [SM]   [0] Call_PushCell
L 03/28/2018 - 12:01:42: [SM]   [1] Line 225, vip/VipMenu.sp::Handler_VIPMenu
L 03/28/2018 - 12:01:42: [SM]   [3] Menu.DisplayAt
L 03/28/2018 - 12:01:42: [SM]   [4] Line 306, vip/VipMenu.sp::Handler_VIPMenu
L 03/28/2018 - 12:01:42: [SM] Exception reported: Cannot finish call when there is no call in progress
L 03/28/2018 - 12:01:42: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 12:01:42: [SM] Call stack trace:
L 03/28/2018 - 12:01:42: [SM]   [0] Call_Finish
L 03/28/2018 - 12:01:42: [SM]   [1] Line 226, vip/VipMenu.sp::Handler_VIPMenu
L 03/28/2018 - 12:01:42: [SM]   [3] Menu.DisplayAt
L 03/28/2018 - 12:01:42: [SM]   [4] Line 306, vip/VipMenu.sp::Handler_VIPMenu

UPD #2 : Думаю смысла писать нет, но все же

> L 03/28/2018 - 11:43:18: [SM] Exception reported: Language phrase "LOG_ADMIN_VIP_IDENTITY_DELETED" not found (arg 5)
L 03/28/2018 - 11:43:18: [SM] Blaming: VIP_Core.smx
L 03/28/2018 - 11:43:18: [SM] Call stack trace:
L 03/28/2018 - 11:43:18: [SM]   [0] LogToFile
L 03/28/2018 - 11:43:18: [SM]   [1] Line 287, vip/Database.sp::SQL_Callback_RemoveClient
L 03/28/2018 - 11:43:18: [VIP_Core.smx] T�����P�8

**Comment by R1KO** [comment]
вы не обновили файл перевода ядра
