### ISSUE TITLE
VIP_UnregisterMe()

### ISSUE THREAD

**Issue by CrazyHackGUT** [R1KO/VIP-Core#21]
Add native `VIP_UnregisterMe()` which removes the registration of all the functions of the module that calls this native. Like `Shop_UnregisterMe()` in **[Shop] Core** from FrozDark.

**Comment by R1KO** [comment]
Давно уже добавлено:
https://github.com/R1KO/VIP-Core/commit/7ba58b89b1fc45edeac9953e16e562d86607bd0e
