### ISSUE TITLE
SQLite fallback broken

### ISSUE THREAD

**Issue by CrazyHackGUT** [R1KO/VIP-Core#32]
See https://github.com/alliedmodders/sourcemod/issues/865 for more details.
https://github.com/R1KO/VIP-Core/blob/11bb1fec61e0d9ab2ab388c5011d1de7e5000d35/addons/sourcemod/scripting/vip/Database.sp#L23-L33

**Comment by R1KO** [comment]
@CrazyHackGUT это еще актуально или можно закрывать?

**Comment by CrazyHackGUT** [comment]
Неактуально. Они вернули старое поведение.
