### ISSUE TITLE
Call_StartFunction

### ISSUE THREAD

**Issue by valeologist** [R1KO/VIP-Core#35]
L 10/22/2018 - 19:25:46: [SM] Exception reported: Plugin handle 6e006e is invalid (error 1)
L 10/22/2018 - 19:25:46: [SM] Blaming: vip/VIP_Core.smx
L 10/22/2018 - 19:25:46: [SM] Call stack trace:
L 10/22/2018 - 19:25:46: [SM]   [0] Call_StartFunction
L 10/22/2018 - 19:25:46: [SM]   [1] Line 168, vip/API.sp::Function_OnItemToggle
L 10/22/2018 - 19:25:46: [SM]   [2] Line 63, vip/Features.sp::Features_TurnOnAll
L 10/22/2018 - 19:25:46: [SM]   [3] Line 194, vip/Clients.sp::Clients_OnVIPClientLoaded
L 10/22/2018 - 19:25:46: [SM]   [4] Line 298, vip/Clients.sp::Clients_LoadVIPFeatures
L 10/22/2018 - 19:25:46: [SM]   [5] Line 627, vip/API.sp::API_GiveClientVIP
L 10/22/2018 - 19:25:46: [SM]   [6] Line 554, vip/API.sp::Native_GiveClientVIP
L 10/22/2018 - 19:25:46: [SM]   [8] VIP_GiveClientVIP
L 10/22/2018 - 19:25:46: [SM]   [9] Line 200, VIP_Admin_1.1.sp::GiveVIPClient
L 10/22/2018 - 19:25:46: [SM]   [10] Line 122, VIP_Admin_1.1.sp::CheckClient
L 10/22/2018 - 19:25:46: [SM]   [11] Line 104, VIP_Admin_1.1.sp::Timer_Delay

**Comment by CrazyHackGUT** [comment]
Один из модулей кривой.
Список модулей в студию.

**Comment by valeologist** [comment]
> 
> 
> Один из модулей кривой.
> Список модулей в студию.

23 "[SWGM] VIP" (1.4) by Someone
35 "[VIP] Electro Effects" (1.0.3) by R1KO
36 "[VIP] GrenadeTrails" (1.0.1) by R1KO
37 "[VIP] Vips Online" (1.0.1) by R1KO (skype: vova.andrienko1)
38 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
39 "[VIP] Test" (1.1) by R1KO (skype: vova.andrienko1)
40 "[VIP] Spawn Effects" (1.2) by Mr.ToNik
41 "[VIP] No Fall Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
42 "[VIP] Admin" (1.1) by R1KO
43 "[VIP] Drop Weapons" (1.1) by R1KO
44 "[VIP] Core" (3.0 R) by R1KO
57 "[VIP] Bhop" (1.0.1) by KOROVKA
58 "[VIP] Regen HP" (1.0.4) by R1KO
59 "[VIP] Regen Armor" (1.0.4) by R1KO
60 "[VIP] Throwing Knives" (1.0.5) by R1KO (original by meng, Bacardi)
61 "Knife Fight" (1.0) by DRUID
62 "Weapon Restrict" (4.0.0-b4) by Dr!fter

**Comment by R1KO** [comment]
@valeologist буду обновлять по порядку. посмотрим что виновато

**Comment by valeologist** [comment]
> 
> 
> @valeologist буду обновлять по порядку. посмотрим что виновато

Хорошо! ) Я очень жду )
