### ISSUE TITLE
Ветка internal_store не компилится

### ISSUE THREAD

**Issue by Septembers** [R1KO/VIP-Core#38]
Ветка internal_store не компилится

http://prntscr.com/m8hsd9

**Comment by R1KO** [comment]
@Septembers https://gitlab.com/vip-r1ko/VIP-Core/tree/internal_store

**Comment by CrazyHackGUT** [comment]
@R1KO заархивируй репу тогда, если последние исходники недоступны здесь.

**Comment by R1KO** [comment]
@CrazyHackGUT доступны, кроме этой ветки.

**Comment by CrazyHackGUT** [comment]
Почему тогда мастер здесь, на Гитхабе, последний раз обновлялся в сентябре (4 месяца назад приблизительно), а на Гитлабе - 2 месяца назад?

**Comment by R1KO** [comment]
@CrazyHackGUT потому что правки не затрагивали код https://gitlab.com/vip-r1ko/VIP-Core/commit/d6f4672c106f760dee05c64fc79d32f81b54cc12

когда полностью всё перенесу на гитлаб тогда и архивну репу
