### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by megoRU** [R1KO/VIP-Core#41]
![image](https://user-images.githubusercontent.com/23276305/55098284-8c5e8300-50ce-11e9-8e4d-7e229bc698de.png)

**Comment by R1KO** [comment]
компилить нужно на см 1.10

**Comment by CrazyHackGUT** [comment]
Так этот натив есть и в последнем 1.9.
https://github.com/alliedmodders/sourcemod/blob/1.9-dev/plugins/include/lang.inc#L118-L125
