### ISSUE TITLE
MarkNativeAsOptional

### ISSUE THREAD

**Issue by dragokas** [R1KO/VIP-Core#47]
https://github.com/R1KO/VIP-Core/blob/master/addons/sourcemod/scripting/include/vip_core.inc

please, add:

MarkNativeAsOptional("VIP_GiveClientVIP");
MarkNativeAsOptional("VIP_UnregisterMe");
MarkNativeAsOptional("VIP_GiveClientFeature");
MarkNativeAsOptional("VIP_RemoveClientFeature");

**Comment by R1KO** [comment]
@dragokas pull request please :)

**Comment by dragokas** [comment]
https://github.com/R1KO/VIP-Core/pull/48

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/pull/48
