### ISSUE TITLE
VIP Chat (+SCP) 

### ISSUE THREAD

**Issue by G0dFulL** [R1KO/VIP-Core#56]
Well, hello everyone my VIP Chat was configured and everything seems to work but one thing doesnt. When i enable all of those like prefix, name color, chat color and all of those arent working do you have any idea why?

**Comment by R1KO** [comment]
@G0dFulL it's issue has been fixed?

**Comment by G0dFulL** [comment]
@R1KO yes man, i didnt install SCP .... now its on. Thank you anyways :)
