### ISSUE TITLE
Bug with "VIP_FillArrayByFeatures"

### ISSUE THREAD

**Issue by IL0co** [R1KO/VIP-Core#59]
When you create a new empty ArrayList
`ArrayList arFeatures = new ArrayList();`
and you throw it into the native "VIP_FillArrayByFeatures", then it returns the feature name cut to 4 characters instead of the full name

**Comment by R1KO** [comment]
This is your problem.
Use `ArrayList arFeatures = new ArrayList(ByteCountToCells(32));`
