### ISSUE TITLE
Хранение VIP-пользователей

### ISSUE THREAD

**Issue by CrazyHackGUT** [R1KO/VIP-Core#6]
**Кратко: что сейчас?**
Сейчас [VIP] Core хранит у пользователей `AuthId_Engine`, что может вызывать проблемы, если БД на нескольких серверах в разных играх общая. Для примера, TF2 хранит `AuthId_Steam3`, CSGO - `AuthId_Steam2`. При выдаче випки кому-либо, будет создаваться новая запись в БД в таблице юзеров для того же игрока.

**Что я предлагаю?**
Заменить использование `GetClientAuthId()` на `GetSteamAccountID()` везде, начать хранить ID аккаунта, на основе которого и базируется любой вид SteamID. Куда проще хранить и работать с _integer_, чем строку.
Это, возможно, потребует полного пересоздавания БД администратором, либо добавление запросов на изменение колонки и перезаписи игроков в таблицу. Но оно того стоит.

**Comment by R1KO** [comment]
Изначально так и планировал. Но это вынудит изменить структуру базы и следовательно при обновлении пользователей придется портировать. Я думаю так: раз изменять базу то лучше сразу сделать и поддержку нескольких групп для одного игрока, чтобы админы не страдали от постоянных изменений базы

**Comment by R1KO** [comment]
https://github.com/R1KO/VIP-Core/commit/7c180fbc3098e41a0dfc502758fc05c344d1e6df
