### ISSUE TITLE
Implement access to certain privilege groups

### ISSUE THREAD

**Issue by crashzk** [R1KO/VIP-Core#74]
Currently players with access to the flag set in the **`sm_vip_admin_flag`** cvar would have root access to the VIP Core.
```
// Флаг админа, необходимый чтобы иметь доступ к управлению VIP-игроками.
// -
// Default: "z"
sm_vip_admin_flag "n"
```
In my file **`groups.ini`** located in the folder **`csgo/addons/sourcemod/data/vip/cfg`** in addition to the **VIP** group of privileges I have others, such as **OWNER, DEV, ADMIN & MOD**.

However players with access to the **`n`** flag would only have two groups, **OWNERS & DEVS**, these two groups can place any privilege group configured in **`groups.ini`** in the players.

I would like to have some way of limiting the privilege groups **DEVS** to have access to put privilege group only of **VIPS**, groups like **OWNER, DEV, ADMIN & MOD** only players with access to OWNER group would have access to place these.

Would such a thing be possible today, or would it need to be implemented?

**Comment by R1KO** [comment]
@crashzk do not give out this admin flag to VIP-players or change it to another

**Comment by crashzk** [comment]
> @crashzk do not give out this admin flag to VIP-players or change it to another

Yes, I understand that. Currently only two groups have access to the admin flag, being OWNER and DEV, none of them has the flag.

However, as DEV has this admin flag the plugin gives him access to put the DONO group for himself, in this case he wanted to block it, that is, even if he has the admin flag for the DONO position he will not have access to put this group on him or other players.
