### ISSUE TITLE
[ERROR] - List.sp::ShowTargetInfoMenu and List.sp::SQL_Callback_SelectVipClientInfo

### ISSUE THREAD

**Issue by andrew2kRO** [R1KO/VIP-Core#78]
2/02/2021 - 09:57:58: [SM] Blaming: VIP_Core.smx
02/02/2021 - 09:57:58: [SM] Call stack trace:
02/02/2021 - 09:57:58: [SM][0] Menu.SetTitle
02/02/2021 - 09:57:58: [SM][1] Line 433, C:\Users\Razvan\AppData\Roaming\spedit\sourcepawn\configs\sm_1_10\include\vip/adminmenu/List.sp::ShowTargetInfoMenu
02/02/2021 - 09:57:58: [SM][2] Line 363, C:\Users\Razvan\AppData\Roaming\spedit\sourcepawn\configs\sm_1_10\include\vip/adminmenu/List.sp::SQL_Callback_SelectVipClientInfo

**Comment by R1KO** [comment]
@andrew2kRO ошибка начинается с  "Exception reported"
