### ISSUE TITLE
[solved/исправлено] vip admin menu

### ISSUE THREAD

**Issue by TOWUK** [R1KO/VIP-Core#94]
just see it: https://youtu.be/RvWUo1e8JYU
last version **vip core** + dev **sm** and **meta**
![изображение](https://user-images.githubusercontent.com/28830162/137973339-97839fa7-a59e-427e-b467-f8181d80dfa7.png)
![изображение](https://user-images.githubusercontent.com/28830162/137973352-7c8dc2ef-a541-4e22-82eb-96f1fb7aa908.png)
![изображение](https://user-images.githubusercontent.com/28830162/137973373-4e1fc7ec-7ae3-49b6-b88b-e54b60dc350e.png)
![изображение](https://user-images.githubusercontent.com/28830162/137973382-49dd2191-8e3c-4539-9318-117dab291bf3.png)

**Comment by R1KO** [comment]
@TOWUK check error logs & give me vip/cfg/groups.ini

**Comment by TOWUK** [comment]
lol i am just remove in admin_sorting vip_admin selection
